import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import BillingView from './BillingView';
import HousekeepingView from './HousekeepingView';
import ReportsView from './ReportsView';

type User = { id: number; username: string; role: string };
type Dashboard = { business_date: string; total_rooms: number; available_rooms: number; reserved_rooms: number; occupied_rooms: number; dirty_rooms: number; out_of_order_rooms: number; arrivals_today: number; departures_today: number; in_house_guests: number };
type RoomType = { id: number; name: string; base_rate: number; description?: string | null };
type Room = { id: number; number: string; room_type_id: number; status: string };
type Guest = { id: number; full_name: string; phone?: string | null; email?: string | null; address?: string | null; id_document?: string | null };
type Reservation = { id: number; guest_id: number; guest_name: string; check_in: string; check_out: string; status: string; room_ids: number[]; folio_id: number };
type FrontDeskData = { arrivals: Reservation[]; departures: Reservation[]; in_house: Reservation[] };
type BillingSummary = { folio_id: number; reservation_id: number; guest_name: string; status: string; total: number; paid: number; balance: number };
type AuthMode = 'login' | 'bootstrap';
type View = 'Dashboard' | 'Rooms' | 'Guests' | 'Reservations' | 'Front Desk' | 'Housekeeping' | 'Reports' | 'Billing';

const modules: View[] = ['Dashboard', 'Rooms', 'Guests', 'Reservations', 'Front Desk', 'Housekeeping', 'Reports', 'Billing'];
const TOKEN_KEY = 'la_serene_access_token';
const statuses = ['available', 'reserved', 'occupied', 'dirty', 'out_of_order'] as const;

async function api<T>(path: string, options: RequestInit = {}): Promise<T> {
  const token = localStorage.getItem(TOKEN_KEY);
  const headers = new Headers(options.headers);
  headers.set('Content-Type', 'application/json');
  if (token) headers.set('Authorization', `Bearer ${token}`);
  const response = await fetch(path, { ...options, headers });
  if (!response.ok) {
    let detail = `Request failed (${response.status})`;
    try { detail = (await response.json()).detail ?? detail; } catch { /* ignore */ }
    const error = new Error(detail) as Error & { status?: number };
    error.status = response.status;
    throw error;
  }
  return response.json() as Promise<T>;
}

function AuthScreen({ mode, setMode, onAuthenticated }: { mode: AuthMode; setMode: (mode: AuthMode) => void; onAuthenticated: (user: User, token: string) => void }) {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  async function submit(event: React.FormEvent) {
    event.preventDefault(); setError(''); setBusy(true);
    try {
      if (mode === 'bootstrap') await api('/api/auth/bootstrap-admin', { method: 'POST', body: JSON.stringify({ username, password }) });
      const login = await api<{ access_token: string; user_id: number; username: string; role: string }>('/api/auth/login', { method: 'POST', body: JSON.stringify({ username, password }) });
      onAuthenticated({ id: login.user_id, username: login.username, role: login.role }, login.access_token);
    } catch (err) { setError(err instanceof Error ? err.message : 'Something went wrong'); }
    finally { setBusy(false); }
  }
  return <main className="auth-shell"><section className="auth-card"><p className="eyebrow">LA SERENE HOTEL</p><h1>{mode === 'bootstrap' ? 'Create your admin account' : 'Welcome back'}</h1><p className="muted">{mode === 'bootstrap' ? 'Create the first administrator for this local installation.' : 'Sign in to continue to hotel operations.'}</p><form onSubmit={submit} className="auth-form"><label>Username<input value={username} onChange={e => setUsername(e.target.value)} required minLength={3} /></label><label>Password<input type="password" value={password} onChange={e => setPassword(e.target.value)} required minLength={mode === 'bootstrap' ? 8 : 1} /></label>{error && <p className="form-error">{error}</p>}<button className="primary-button" disabled={busy}>{busy ? 'Please wait…' : mode === 'bootstrap' ? 'Create admin & sign in' : 'Sign in'}</button></form><button className="link-button" onClick={() => { setError(''); setMode(mode === 'login' ? 'bootstrap' : 'login'); }}>{mode === 'login' ? 'New installation? Create the first admin' : 'Already initialized? Sign in instead'}</button></section></main>;
}

function DashboardView({ dashboard, rooms, roomTypes }: { dashboard: Dashboard | null; rooms: Room[]; roomTypes: RoomType[] }) {
  const typeById = useMemo(() => new Map(roomTypes.map(t => [t.id, t])), [roomTypes]);
  const label = (status: string) => status.replace(/_/g, ' ');
  return <><section className="stats">{[['Total Rooms', dashboard?.total_rooms], ['Available', dashboard?.available_rooms], ['Occupied', dashboard?.occupied_rooms], ['Reserved', dashboard?.reserved_rooms], ['Arrivals', dashboard?.arrivals_today], ['Departures', dashboard?.departures_today]].map(([name, value]) => <article className="stat" key={name as string}><span>{name}</span><strong>{value ?? '—'}</strong></article>)}</section><section className="workspace"><div className="panel"><div className="panel-head"><h2>Room Status</h2><span>{rooms.length} rooms</span></div><div className="rooms">{rooms.length ? rooms.map(room => <div className={`room room-${room.status}`} key={room.id}><strong>{room.number}</strong><span>{typeById.get(room.room_type_id)?.name ?? 'Unassigned'} · {label(room.status)}</span></div>) : <p className="muted">No rooms configured yet.</p>}</div></div><div className="panel"><div className="panel-head"><h2>Operations</h2></div><div className="operations"><div><span>Dirty rooms</span><strong>{dashboard?.dirty_rooms ?? '—'}</strong></div><div><span>Out of order</span><strong>{dashboard?.out_of_order_rooms ?? '—'}</strong></div><div><span>In-house guests</span><strong>{dashboard?.in_house_guests ?? '—'}</strong></div></div></div></section></>;
}

function GuestsView({ user, guests, setGuests, onRefresh }: { user: User; guests: Guest[]; setGuests: React.Dispatch<React.SetStateAction<Guest[]>>; onRefresh: () => Promise<void> }) {
  const [query, setQuery] = useState('');
  const [form, setForm] = useState({ full_name: '', phone: '', email: '', address: '', id_document: '' });
  const [message, setMessage] = useState('');
  const canCreate = user.role === 'admin' || user.role === 'reception';
  async function search(event: React.FormEvent) { event.preventDefault(); try { setGuests(await api<Guest[]>(`/api/guests?q=${encodeURIComponent(query)}`)); } catch (err) { setMessage(err instanceof Error ? err.message : 'Search failed'); } }
  async function create(event: React.FormEvent) { event.preventDefault(); try { await api('/api/guests', { method: 'POST', body: JSON.stringify({ ...form, phone: form.phone || null, email: form.email || null, address: form.address || null, id_document: form.id_document || null }) }); setForm({ full_name: '', phone: '', email: '', address: '', id_document: '' }); setMessage('Guest created.'); await onRefresh(); } catch (err) { setMessage(err instanceof Error ? err.message : 'Unable to create guest'); } }
  return <section className="page"><div className="page-heading"><div><p className="muted">Guest records</p><h2>Guests</h2></div><span className="room-count">{guests.length} records</span></div>{message && <p className="notice">{message}</p>}<div className="content-layout"><div className="panel"><form className="search-bar" onSubmit={search}><input placeholder="Search name, phone or email" value={query} onChange={e => setQuery(e.target.value)} /><button className="secondary-button">Search</button></form><div className="guest-list">{guests.length ? guests.map(g => <article key={g.id}><div><strong>{g.full_name}</strong><span>{g.phone || 'No phone'} · {g.email || 'No email'}</span></div><small>{g.id_document || 'No ID document recorded'}</small></article>) : <p className="muted">No guests found.</p>}</div></div>{canCreate && <form className="panel form-panel" onSubmit={create}><div className="panel-head"><h2>New guest</h2></div>{([['full_name','Full name'],['phone','Phone'],['email','Email'],['address','Address'],['id_document','ID document']] as const).map(([key,label]) => <label key={key}>{label}{key === 'address' ? <textarea value={form[key]} onChange={e => setForm({...form, [key]: e.target.value})} rows={2} /> : <input type={key === 'email' ? 'email' : 'text'} value={form[key]} onChange={e => setForm({...form, [key]: e.target.value})} required={key === 'full_name'} />}</label>)}<button className="primary-button">Create guest</button></form>}</div></section>;
}

function ReservationsView({ user, guests, rooms, roomTypes, reservations, onRefresh }: { user: User; guests: Guest[]; rooms: Room[]; roomTypes: RoomType[]; reservations: Reservation[]; onRefresh: () => Promise<void> }) {
  const today = new Date().toISOString().slice(0, 10);
  const [checkIn, setCheckIn] = useState(today); const [checkOut, setCheckOut] = useState(''); const [guestId, setGuestId] = useState(''); const [roomIds, setRoomIds] = useState<number[]>([]); const [available, setAvailable] = useState<Room[]>([]); const [notes, setNotes] = useState(''); const [message, setMessage] = useState('');
  const typeById = useMemo(() => new Map(roomTypes.map(t => [t.id, t])), [roomTypes]); const canCreate = user.role === 'admin' || user.role === 'reception';
  async function findAvailable() { setMessage(''); setRoomIds([]); if (!checkOut) { setMessage('Select a check-out date.'); return; } try { const r = await api<{ rooms: Room[] }>(`/api/availability?check_in=${checkIn}&check_out=${checkOut}`); setAvailable(r.rooms); if (!r.rooms.length) setMessage('No rooms available for those dates.'); } catch (err) { setMessage(err instanceof Error ? err.message : 'Availability check failed'); } }
  async function create(event: React.FormEvent) { event.preventDefault(); try { await api('/api/reservations', { method: 'POST', body: JSON.stringify({ guest_id: Number(guestId), check_in: checkIn, check_out: checkOut, room_ids: roomIds, notes: notes || null }) }); setMessage('Reservation created.'); setGuestId(''); setRoomIds([]); setAvailable([]); setNotes(''); await onRefresh(); } catch (err) { setMessage(err instanceof Error ? err.message : 'Unable to create reservation'); } }
  const toggle = (id: number) => setRoomIds(current => current.includes(id) ? current.filter(x => x !== id) : [...current, id]);
  return <section className="page"><div className="page-heading"><div><p className="muted">Bookings & availability</p><h2>Reservations</h2></div><span className="room-count">{reservations.length} bookings</span></div>{message && <p className="notice">{message}</p>}<div className="content-layout"><div className="panel"><div className="panel-head"><h2>Reservation register</h2></div><div className="reservation-list">{reservations.length ? reservations.map(r => <article key={r.id}><div><strong>#{r.id} · {r.guest_name}</strong><span>{r.check_in} → {r.check_out} · {r.room_ids.map(id => rooms.find(room => room.id === id)?.number ?? id).join(', ')}</span></div><b>{r.status}</b></article>) : <p className="muted">No reservations yet.</p>}</div></div>{canCreate && <form className="panel form-panel" onSubmit={create}><div className="panel-head"><h2>New reservation</h2></div><label>Guest<select value={guestId} onChange={e => setGuestId(e.target.value)} required><option value="">Select guest</option>{guests.map(g => <option key={g.id} value={g.id}>{g.full_name}</option>)}</select></label><div className="two-col"><label>Check-in<input type="date" value={checkIn} onChange={e => setCheckIn(e.target.value)} required /></label><label>Check-out<input type="date" value={checkOut} onChange={e => setCheckOut(e.target.value)} required /></label></div><button type="button" className="secondary-button" onClick={findAvailable}>Check availability</button>{available.length > 0 && <div className="availability-picker">{available.map(room => <button type="button" key={room.id} className={roomIds.includes(room.id) ? 'selected' : ''} onClick={() => toggle(room.id)}><strong>{room.number}</strong><span>{typeById.get(room.room_type_id)?.name ?? 'Room'}</span></button>)}</div>}<label>Notes<textarea value={notes} onChange={e => setNotes(e.target.value)} rows={2} /></label><button className="primary-button" disabled={!guestId || !roomIds.length || !checkOut || checkOut <= checkIn}>Create reservation</button></form>}</div></section>;
}

function FrontDeskView({ user, data, rooms, onRefresh }: { user: User; data: FrontDeskData; rooms: Room[]; onRefresh: () => Promise<void> }) {
  const canOperate = user.role === 'admin' || user.role === 'reception'; const [message, setMessage] = useState(''); const [transferReservation, setTransferReservation] = useState<number | null>(null); const [fromRoom, setFromRoom] = useState(''); const [toRoom, setToRoom] = useState(''); const roomById = useMemo(() => new Map(rooms.map(r => [r.id, r])), [rooms]);
  async function action(r: Reservation, actionName: 'check-in' | 'check-out') { try { await api(`/api/reservations/${r.id}/${actionName}`, { method: 'POST' }); setMessage(`Reservation #${r.id} ${actionName === 'check-in' ? 'checked in' : 'checked out'}.`); await onRefresh(); } catch (err) { setMessage(err instanceof Error ? err.message : `Unable to ${actionName}`); } }
  async function transfer(e: React.FormEvent) { e.preventDefault(); if (!transferReservation || !fromRoom || !toRoom) return; try { await api(`/api/reservations/${transferReservation}/transfer`, { method: 'POST', body: JSON.stringify({ from_room_id: Number(fromRoom), to_room_id: Number(toRoom) }) }); setMessage(`Reservation #${transferReservation} transferred.`); setTransferReservation(null); await onRefresh(); } catch (err) { setMessage(err instanceof Error ? err.message : 'Unable to transfer room'); } }
  const card = (r: Reservation, kind: 'arrival' | 'departure' | 'in-house') => <article className="desk-card" key={r.id}><div><strong>#{r.id} · {r.guest_name}</strong><span>{r.check_in} → {r.check_out}</span><small>Room(s): {r.room_ids.map(id => roomById.get(id)?.number ?? id).join(', ')}</small></div><div className="desk-actions">{kind === 'arrival' && canOperate && <button className="primary-button small-button" onClick={() => action(r,'check-in')}>Check in</button>}{kind === 'departure' && canOperate && <button className="primary-button small-button" onClick={() => action(r,'check-out')}>Check out</button>}{kind === 'in-house' && canOperate && r.room_ids.map(id => <button key={id} className="secondary-button small-button" onClick={() => { setTransferReservation(r.id); setFromRoom(String(id)); setToRoom(''); }}>Transfer room</button>)}</div></article>;
  return <section className="page"><div className="page-heading"><div><p className="muted">Guest movement and room operations</p><h2>Front Desk</h2></div><span className="room-count">{data.in_house.length} in house</span></div>{message && <p className="notice">{message}</p>}{transferReservation !== null && <form className="panel transfer-panel" onSubmit={transfer}><div className="panel-head"><h2>Transfer room · #{transferReservation}</h2><button type="button" className="link-button" onClick={() => setTransferReservation(null)}>Cancel</button></div><div className="two-col"><label>Current room<select value={fromRoom} onChange={e => setFromRoom(e.target.value)}><option value="">Select</option>{(data.in_house.find(r => r.id === transferReservation)?.room_ids ?? []).map(id => <option key={id} value={id}>{roomById.get(id)?.number ?? id}</option>)}</select></label><label>New room<select value={toRoom} onChange={e => setToRoom(e.target.value)}><option value="">Select available room</option>{rooms.filter(r => r.status === 'available').map(r => <option key={r.id} value={r.id}>{r.number}</option>)}</select></label></div><button className="primary-button" disabled={!fromRoom || !toRoom}>Confirm transfer</button></form>}<div className="desk-grid"><div className="panel"><div className="panel-head"><h2>Arrivals</h2><span>{data.arrivals.length}</span></div>{data.arrivals.length ? data.arrivals.map(r => card(r,'arrival')) : <p className="muted">No arrivals today.</p>}</div><div className="panel"><div className="panel-head"><h2>Departures</h2><span>{data.departures.length}</span></div>{data.departures.length ? data.departures.map(r => card(r,'departure')) : <p className="muted">No departures today.</p>}</div><div className="panel"><div className="panel-head"><h2>In house</h2><span>{data.in_house.length}</span></div>{data.in_house.length ? data.in_house.map(r => card(r,'in-house')) : <p className="muted">No checked-in guests.</p>}</div></div></section>;
}

function RoomsView({ user, rooms, setRooms, roomTypes, onRefresh }: { user: User; rooms: Room[]; setRooms: React.Dispatch<React.SetStateAction<Room[]>>; roomTypes: RoomType[]; onRefresh: () => Promise<void> }) {
  const [filter, setFilter] = useState('all'); const [message, setMessage] = useState(''); const [typeName, setTypeName] = useState(''); const [rate, setRate] = useState(''); const [desc, setDesc] = useState(''); const [number, setNumber] = useState(''); const [typeId, setTypeId] = useState(''); const typeById = useMemo(() => new Map(roomTypes.map(t => [t.id, t])), [roomTypes]); const admin = user.role === 'admin';
  async function createType(e: React.FormEvent) { e.preventDefault(); try { await api('/api/room-types',{method:'POST',body:JSON.stringify({name:typeName,base_rate:Number(rate||0),description:desc||null})}); setTypeName('');setRate('');setDesc('');setMessage('Room type created.');await onRefresh(); } catch(err){setMessage(err instanceof Error?err.message:'Unable to create room type');} }
  async function createRoom(e: React.FormEvent) { e.preventDefault(); try { await api('/api/rooms',{method:'POST',body:JSON.stringify({number,room_type_id:Number(typeId)})});setNumber('');setTypeId('');setMessage('Room added.');await onRefresh();} catch(err){setMessage(err instanceof Error?err.message:'Unable to add room');} }
  async function changeStatus(room:Room,next:string){try{const updated=await api<Room>(`/api/rooms/${room.id}/status`,{method:'PATCH',body:JSON.stringify({status:next})});setRooms(cur=>cur.map(r=>r.id===updated.id?updated:r));setMessage(`Room ${updated.number} is now ${next.replace(/_/g,' ')}.`);}catch(err){setMessage(err instanceof Error?err.message:'Unable to change status');}}
  const visible=filter==='all'?rooms:rooms.filter(r=>r.status===filter);
  return <section className="page"><div className="page-heading"><div><p className="muted">Inventory & housekeeping</p><h2>Rooms</h2></div><span className="room-count">{rooms.length} rooms</span></div>{message&&<p className="notice">{message}</p>}<div className="room-layout"><div className="panel"><div className="panel-head"><h2>Room map</h2><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All statuses</option>{statuses.map(s=><option key={s} value={s}>{s.replace(/_/g,' ')}</option>)}</select></div><div className="room-map">{visible.length?visible.map(room=><article className={`room-card room-${room.status}`} key={room.id}><div className="room-card-top"><strong>{room.number}</strong><span>{typeById.get(room.room_type_id)?.name??'Unknown type'}</span></div><small>{typeById.get(room.room_type_id)?Number(typeById.get(room.room_type_id)!.base_rate).toFixed(2):'No rate'}</small><select value={room.status} onChange={e=>changeStatus(room,e.target.value)}>{statuses.map(s=><option key={s} value={s}>{s.replace(/_/g,' ')}</option>)}</select></article>):<p className="muted">No rooms match this filter.</p>}</div></div><div className="side-stack"><div className="panel"><div className="panel-head"><h2>Room types</h2><span>{roomTypes.length}</span></div>{roomTypes.map(t=><div className="type-row" key={t.id}><strong>{t.name}</strong><b>{Number(t.base_rate).toFixed(2)}</b></div>)}</div>{admin&&<><form className="panel form-panel" onSubmit={createType}><div className="panel-head"><h2>Add room type</h2></div><label>Name<input value={typeName} onChange={e=>setTypeName(e.target.value)} required /></label><label>Base rate<input type="number" min="0" step="0.01" value={rate} onChange={e=>setRate(e.target.value)} required /></label><label>Description<textarea value={desc} onChange={e=>setDesc(e.target.value)} rows={2}/></label><button className="primary-button">Create room type</button></form><form className="panel form-panel" onSubmit={createRoom}><div className="panel-head"><h2>Add room</h2></div><label>Room number<input value={number} onChange={e=>setNumber(e.target.value)} required /></label><label>Room type<select value={typeId} onChange={e=>setTypeId(e.target.value)} required><option value="">Select type</option>{roomTypes.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><button className="primary-button" disabled={!roomTypes.length}>Add room</button></form></>}</div></div></section>;
}

function App(){
  const [user,setUser]=useState<User|null>(null); const [authMode,setAuthMode]=useState<AuthMode>('login'); const [checking,setChecking]=useState(true); const [dashboard,setDashboard]=useState<Dashboard|null>(null); const [rooms,setRooms]=useState<Room[]>([]); const [roomTypes,setRoomTypes]=useState<RoomType[]>([]); const [guests,setGuests]=useState<Guest[]>([]); const [reservations,setReservations]=useState<Reservation[]>([]); const [frontDesk,setFrontDesk]=useState<FrontDeskData>({arrivals:[],departures:[],in_house:[]}); const [billing,setBilling]=useState<BillingSummary[]>([]); const [view,setView]=useState<View>('Dashboard'); const [error,setError]=useState('');
  const visibleModules = user?.role === 'admin' || user?.role === 'reception' ? modules : modules.filter(module => module !== 'Billing' && module !== 'Reports');
  async function refresh(){
    const [d,r,rt,g,rs,fd] = await Promise.all([
      api<Dashboard>('/api/dashboard'),
      api<Room[]>('/api/rooms'),
      api<RoomType[]>('/api/room-types'),
      api<Guest[]>('/api/guests'),
      api<Reservation[]>('/api/reservations'),
      api<FrontDeskData>('/api/front-desk'),
    ]);
    setDashboard(d);setRooms(r);setRoomTypes(rt);setGuests(g);setReservations(rs);setFrontDesk(fd);
    if (user?.role === 'admin' || user?.role === 'reception') setBilling(await api<BillingSummary[]>('/api/billing')); else setBilling([]);
  }
  useEffect(()=>{const token=localStorage.getItem(TOKEN_KEY);if(!token){api<{initialized:boolean}>('/api/auth/setup-status').then(s=>setAuthMode(s.initialized?'login':'bootstrap')).catch(()=>setError('Backend is not running.')).finally(()=>setChecking(false));return;}api<User>('/api/auth/me').then(setUser).catch(()=>localStorage.removeItem(TOKEN_KEY)).finally(()=>setChecking(false));},[]);
  useEffect(()=>{if(!user)return;refresh().catch(err=>{if((err as Error&{status?:number}).status===401)logout();else setError(err instanceof Error?err.message:'Unable to load hotel data');});},[user]);
  useEffect(()=>{if (!visibleModules.includes(view)) setView('Dashboard');}, [user?.role]);
  function authenticated(next:User,token:string){localStorage.setItem(TOKEN_KEY,token);setUser(next);setView('Dashboard');}
  function logout(){localStorage.removeItem(TOKEN_KEY);setUser(null);setDashboard(null);setRooms([]);setRoomTypes([]);setGuests([]);setReservations([]);setFrontDesk({arrivals:[],departures:[],in_house:[]});setBilling([]);setAuthMode('login');}
  if(checking)return <main className="auth-shell"><p className="muted">Checking local session…</p></main>;
  if(!user)return <AuthScreen mode={authMode} setMode={setAuthMode} onAuthenticated={authenticated}/>;
  return <main className="shell"><header className="topbar"><div><p className="eyebrow">LA SERENE HOTEL</p><h1>Hotel Management System</h1></div><div className="user-actions"><div className="user-chip"><strong>{user.username}</strong><span>{user.role}</span></div><button className="logout-button" onClick={logout}>Log out</button></div></header><nav className="module-nav">{visibleModules.map(m=><button key={m} className={view===m?'active':''} onClick={()=>setView(m)}>{m}</button>)}</nav>{error&&<p className="error">{error}</p>}{view==='Dashboard'&&<><section className="welcome"><div><p className="muted">Operations dashboard</p><h2>{dashboard?`Business date · ${dashboard.business_date}`:'Loading hotel data…'}</h2></div></section><DashboardView dashboard={dashboard} rooms={rooms} roomTypes={roomTypes}/></>}{view==='Rooms'&&<RoomsView user={user} rooms={rooms} setRooms={setRooms} roomTypes={roomTypes} onRefresh={refresh}/>} {view==='Guests'&&<GuestsView user={user} guests={guests} setGuests={setGuests} onRefresh={refresh}/>} {view==='Reservations'&&<ReservationsView user={user} guests={guests} rooms={rooms} roomTypes={roomTypes} reservations={reservations} onRefresh={refresh}/>} {view==='Front Desk'&&<FrontDeskView user={user} data={frontDesk} rooms={rooms} onRefresh={refresh}/>} {view==='Housekeeping'&&<HousekeepingView userRole={user.role} api={api}/>} {view==='Reports'&&<ReportsView api={api}/>} {view==='Billing'&&<BillingView userRole={user.role} summaries={billing} onRefresh={refresh} api={api}/>}</main>;
}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
