import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

type User = { id: number; username: string; role: string };
type Dashboard = { business_date: string; total_rooms: number; available_rooms: number; reserved_rooms: number; occupied_rooms: number; dirty_rooms: number; out_of_order_rooms: number; arrivals_today: number; departures_today: number; in_house_guests: number };
type RoomType = { id: number; name: string; base_rate: number; description?: string | null };
type Room = { id: number; number: string; room_type_id: number; status: string };
type Guest = { id: number; full_name: string; phone?: string | null; email?: string | null; address?: string | null; id_document?: string | null };
type Reservation = { id: number; guest_id: number; guest_name: string; check_in: string; check_out: string; status: string; room_ids: number[]; folio_id: number };
type FrontDeskData = { arrivals: Reservation[]; departures: Reservation[]; in_house: Reservation[] };
type AuthMode = 'login' | 'bootstrap';
type View = 'Dashboard' | 'Rooms' | 'Guests' | 'Reservations' | 'Front Desk';

const modules: View[] = ['Dashboard', 'Rooms', 'Guests', 'Reservations', 'Front Desk'];
const TOKEN_KEY = 'la_serene_access_token';
const statuses = ['available', 'reserved', 'occupied', 'dirty', 'out_of_order'] as const;

async function api<T>(path: string, options: RequestInit = {}): Promise<T> {
  const token = localStorage.getItem(TOKEN_KEY);
  const headers = new Headers(options.headers);
  headers.set('Content-Type', 'application/json');
  if (token) headers.set('Authorization', `Bearer ${token}`);
  const response = await fetch(path, { ...options, headers });
  if (!response.ok) {
    let detail = `Request failed (${response.status})`;
    try { detail = (await response.json()).detail ?? detail; } catch { /* ignore */ }
    const error = new Error(detail) as Error & { status?: number };
    error.status = response.status;
    throw error;
  }
  return response.json() as Promise<T>;
}

function AuthScreen({ mode, setMode, onAuthenticated }: { mode: AuthMode; setMode: (mode: AuthMode) => void; onAuthenticated: (user: User, token: string) => void }) {
  const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(event: React.FormEvent) {
    event.preventDefault(); setError(''); setBusy(true);
    try {
      if (mode === 'bootstrap') await api('/api/auth/bootstrap-admin', { method: 'POST', body: JSON.stringify({ username, password }) });
      const login = await api<{ access_token: string; user_id: number; username: string; role: string }>('/api/auth/login', { method: 'POST', body: JSON.stringify({ username, password }) });
      onAuthenticated({ id: login.user_id, username: login.username, role: login.role }, login.access_token);
    } catch (err) { setError(err instanceof Error ? err.message : 'Something went wrong'); } finally { setBusy(false); }
  }
  return <main className="auth-shell"><section className="auth-card"><p className="eyebrow">LA SERENE HOTEL</p><h1>{mode === 'bootstrap' ? 'Create your admin account' : 'Welcome back'}</h1><p className="muted">{mode === 'bootstrap' ? 'Create the first administrator for this local installation.' : 'Sign in to continue to hotel operations.'}</p><form onSubmit={submit} className="auth-form"><label>Username<input value={username} onChange={e => setUsername(e.target.value)} required minLength={3} autoComplete="username" /></label><label>Password<input type="password" value={password} onChange={e => setPassword(e.target.value)} required minLength={mode === 'bootstrap' ? 8 : 1} autoComplete={mode === 'bootstrap' ? 'new-password' : 'current-password'} /></label>{error && <p className="form-error">{error}</p>}<button className="primary-button" disabled={busy}>{busy ? 'Please wait…' : mode === 'bootstrap' ? 'Create admin & sign in' : 'Sign in'}</button></form><button className="link-button" onClick={() => { setError(''); setMode(mode === 'login' ? 'bootstrap' : 'login'); }}>{mode === 'login' ? 'New installation? Create the first admin' : 'Already initialized? Sign in instead'}</button></section></main>;
}

function DashboardView({ dashboard, rooms, roomTypes }: { dashboard: Dashboard | null; rooms: Room[]; roomTypes: RoomType[] }) {
  const typeById = useMemo(() => new Map(roomTypes.map(t => [t.id, t])), [roomTypes]); const label = (status: string) => status.replace(/_/g, ' ');
  return <><section className="stats">{[['Total Rooms', dashboard?.total_rooms], ['Available', dashboard?.available_rooms], ['Occupied', dashboard?.occupied_rooms], ['Reserved', dashboard?.reserved_rooms], ['Arrivals', dashboard?.arrivals_today], ['Departures', dashboard?.departures_today]].map(([name, value]) => <article className="stat" key={name as string}><span>{name}</span><strong>{value ?? '—'}</strong></article>)}</section><section className="workspace"><div className="panel"><div className="panel-head"><h2>Room Status</h2><span>{rooms.length} rooms</span></div><div className="rooms">{rooms.length ? rooms.map(room => <div className={`room room-${room.status}`} key={room.id}><strong>{room.number}</strong><span>{typeById.get(room.room_type_id)?.name ?? 'Unassigned'} · {label(room.status)}</span></div>) : <p className="muted">No rooms configured yet.</p>}</div></div><div className="panel"><div className="panel-head"><h2>Operations</h2></div><div className="operations"><div><span>Dirty rooms</span><strong>{dashboard?.dirty_rooms ?? '—'}</strong></div><div><span>Out of order</span><strong>{dashboard?.out_of_order_rooms ?? '—'}</strong></div><div><span>In-house guests</span><strong>{dashboard?.in_house_guests ?? '—'}</strong></div></div></div></section></>;
}

function GuestsView({ user, guests, setGuests, onRefresh }: { user: User; guests: Guest[]; setGuests: React.Dispatch<React.SetStateAction<Guest[]>>; onRefresh: () => Promise<void> }) {
  const [query, setQuery] = useState(''); const [name, setName] = useState(''); const [phone, setPhone] = useState(''); const [email, setEmail] = useState(''); const [address, setAddress] = useState(''); const [idDoc, setIdDoc] = useState(''); const [message, setMessage] = useState(''); const canCreate = user.role === 'admin' || user.role === 'reception';
  async function search(event: React.FormEvent) { event.preventDefault(); try { setGuests(await api<Guest[]>(`/api/guests?q=${encodeURIComponent(query)}`)); } catch (err) { setMessage(err instanceof Error ? err.message : 'Search failed'); } }
  async function create(event: React.FormEvent) { event.preventDefault(); setMessage(''); try { await api<Guest>('/api/guests', { method: 'POST', body: JSON.stringify({ full_name: name, phone: phone || null, email: email || null, address: address || null, id_document: idDoc || null }) }); setName(''); setPhone(''); setEmail(''); setAddress(''); setIdDoc(''); setMessage('Guest created.'); await onRefresh(); } catch (err) { setMessage(err instanceof Error ? err.message : 'Unable to create guest'); } }
  return <section className="page"><div className="page-heading"><div><p className="muted">Guest records</p><h2>Guests</h2></div><span className="room-count">{guests.length} records</span></div>{message && <p className="notice">{message}</p>}<div className="content-layout"><div className="panel"><form className="search-bar" onSubmit={search}><input placeholder="Search name, phone or email" value={query} onChange={e => setQuery(e.target.value)} /><button className="secondary-button">Search</button></form><div className="guest-list">{guests.length ? guests.map(g => <article key={g.id}><div><strong>{g.full_name}</strong><span>{g.phone || 'No phone'} · {g.email || 'No email'}</span></div><small>{g.id_document || 'No ID document recorded'}</small></article>) : <p className="muted">No guests found.</p>}</div></div>{canCreate && <form className="panel form-panel" onSubmit={create}><div className="panel-head"><h2>New guest</h2></div><label>Full name<input value={name} onChange={e => setName(e.target.value)} required /></label><label>Phone<input value={phone} onChange={e => setPhone(e.target.value)} /></label><label>Email<input type="email" value={email} onChange={e => setEmail(e.target.value)} /></label><label>Address<textarea value={address} onChange={e => setAddress(e.target.value)} rows={2} /></label><label>ID document<input value={idDoc} onChange={e => setIdDoc(e.target.value)} /></label><button className="primary-button">Create guest</button></form>}</div></section>;
}

function ReservationsView({ user, guests, rooms, roomTypes, reservations, onRefresh }: { user: User; guests: Guest[]; rooms: Room[]; roomTypes: RoomType[]; reservations: Reservation[]; onRefresh: () => Promise<void> }) {
  const today = new Date().toISOString().slice(0, 10); const [checkIn, setCheckIn] = useState(today); const [checkOut, setCheckOut] = useState(today); const [guestId, setGuestId] = useState(''); const [roomIds, setRoomIds] = useState<number[]>([]); const [available, setAvailable] = useState<Room[]>([]); const [notes, setNotes] = useState(''); const [message, setMessage] = useState(''); const typeById = useMemo(() => new Map(roomTypes.map(t => [t.id, t])), [roomTypes]);
  const canCreate = user.role === 'admin' || user.role === 'reception';
  async function findAvailable() { setMessage(''); setRoomIds([]); try { const result = await api<{ rooms: Room[] }>(`/api/availability?check_in=${checkIn}&check_out=${checkOut}`); setAvailable(result.rooms); if (!result.rooms.length) setMessage('No rooms are available for those dates.'); } catch (err) { setMessage(err instanceof Error ? err.message : 'Unable to check availability'); } }
  async function create(event: React.FormEvent) { event.preventDefault(); setMessage(''); try { await api<Reservation>('/api/reservations', { method: 'POST', body: JSON.stringify({ guest_id: Number(guestId), check_in: checkIn, check_out: checkOut, room_ids: roomIds, notes: notes || null }) }); setMessage('Reservation created.'); setGuestId(''); setRoomIds([]); setNotes(''); setAvailable([]); await onRefresh(); } catch (err) { setMessage(err instanceof Error ? err.message : 'Unable to create reservation'); } }
  const toggleRoom = (id: number) => setRoomIds(current => current.includes(id) ? current.filter(x => x !== id) : [...current, id]);
  return <section className="page"><div className="page-heading"><div><p className="muted">Bookings & availability</p><h2>Reservations</h2></div><span className="room-count">{reservations.length} bookings</span></div>{message && <p className="notice">{message}</p>}<div className="content-layout"><div className="panel"><div className="panel-head"><h2>Reservation register</h2></div><div className="reservation-list">{reservations.length ? reservations.map(r => <article key={r.id}><div><strong>#{r.id} · {r.guest_name}</strong><span>{r.check_in} → {r.check_out} · {r.room_ids.map(id => rooms.find(room => room.id === id)?.number ?? id).join(', ')}</span></div><b>{r.status}</b></article>) : <p className="muted">No reservations yet.</p>}</div></div>{canCreate && <form className="panel form-panel" onSubmit={create}><div className="panel-head"><h2>New reservation</h2></div><label>Guest<select value={guestId} onChange={e => setGuestId(e.target.value)} required><option value="">Select guest</option>{guests.map(g => <option key={g.id} value={g.id}>{g.full_name}</option>)}</select></label><div className="two-col"><label>Check-in<input type="date" value={checkIn} onChange={e => setCheckIn(e.target.value)} required /></label><label>Check-out<input type="date" value={checkOut} onChange={e => setCheckOut(e.target.value)} required /></label></div><button type="button" className="secondary-button" onClick={findAvailable}>Check availability</button>{available.length > 0 && <div className="availability-picker">{available.map(room => <button type="button" key={room.id} className={roomIds.includes(room.id) ? 'selected' : ''} onClick={() => toggleRoom(room.id)}><strong>{room.number}</strong><span>{typeById.get(room.room_type_id)?.name ?? 'Room'} · {room.status}</span></button>)}</div>}<label>Notes<textarea value={notes} onChange={e => setNotes(e.target.value)} rows={2} /></label><button className="primary-button" disabled={!guestId || !roomIds.length || checkOut <= checkIn}>Create reservation</button></form>}</div></section>;
}

function FrontDeskView({ user, data, rooms, onRefresh }: { user: User; data: FrontDeskData; rooms: Room[]; onRefresh: () => Promise<void> }) {
  const canOperate = user.role === 'admin' || user.role === 'reception';
  const [message, setMessage] = useState(''); const [transferReservation, setTransferReservation] = useState<number | null>(null); const [fromRoom, setFromRoom] = useState(''); const [toRoom, setToRoom] = useState('');
  const roomById = useMemo(() => new Map(rooms.map(r => [r.id, r])), [rooms]);
  async function action(reservation: Reservation, actionName: 'check-in' | 'check-out') { setMessage(''); try { await api(`/api/reservations/${reservation.id}/${actionName}`, { method: 'POST' }); setMessage(`Reservation #${reservation.id} ${actionName === 'check-in' ? 'checked in' : 'checked out'}.`); await onRefresh(); } catch (err) { setMessage(err instanceof Error ? err.message : `Unable to ${actionName}`); } }
  async function transfer(event: React.FormEvent) { event.preventDefault(); setMessage(''); if (!transferReservation || !fromRoom || !toRoom) return; try { await api(`/api/reservations/${transferReservation}/transfer`, { method: 'POST', body: JSON.stringify({ from_room_id: Number(fromRoom), to_room_id: Number(toRoom) }) }); setMessage(`Reservation #${transferReservation} transferred successfully.`); setTransferReservation(null); setFromRoom(''); setToRoom(''); await onRefresh(); } catch (err) { setMessage(err instanceof Error ? err.message : 'Unable to transfer room'); } }
  const card = (reservation: Reservation, type: 'arrival' | 'departure' | 'in-house') => <article className="desk-card" key={reservation.id}><div><strong>#{reservation.id} · {reservation.guest_name}</strong><span>{reservation.check_in} → {reservation.check_out}</span><small>Room(s): {reservation.room_ids.map(id => roomById.get(id)?.number ?? id).join(', ')}</small></div><div className="desk-actions">{type === 'arrival' && canOperate && <button className="primary-button small-button" onClick={() => action(reservation, 'check-in')}>Check in</button>}{type === 'departure' && canOperate && <button className="primary-button small-button" onClick={() => action(reservation, 'check-out')}>Check out</button>}{type === 'in-house' && canOperate && reservation.room_ids.map(id => <button key={id} className="secondary-button small-button" onClick={() => { setTransferReservation(reservation.id); setFromRoom(String(id)); setToRoom(''); }}>Transfer room</button>)}</div></article>;
  return <section className="page"><div className="page-heading"><div><p className="muted">Today’s arrivals, departures and in-house guests</p><h2>Front Desk</h2></div><span className="room-count">{data.in_house.length} in house</span></div>{message && <p className="notice">{message}</p>}{transferReservation !== null && <form className="panel transfer-panel" onSubmit={transfer}><div className="panel-head"><h2>Transfer room · reservation #{transferReservation}</h2><button type="button" className="link-button" onClick={() => setTransferReservation(null)}>Cancel</button></div><div className="two-col"><label>Current room<select value={fromRoom} onChange={e => setFromRoom(e.target.value)} required>{(data.in_house.find(r => r.id === transferReservation)?.room_ids ?? []).map(id => <option key={id} value={id}>{roomById.get(id)?.number ?? id}</option>)}</select></label><label>New room<select value={toRoom} onChange={e => setToRoom(e.target.value)} required><option value="">Select available room</option>{rooms.filter(r => r.status === 'available').map(room => <option key={room.id} value={room.id}>{room.number}</option>)}</select></label></div><button className="primary-button" disabled={!fromRoom || !toRoom}>Confirm transfer</button></form>}<div className="desk-grid"><div className="panel"><div className="panel-head"><h2>Arrivals</h2><span>{data.arrivals.length}</span></div>{data.arrivals.length ? data.arrivals.map(r => card(r, 'arrival')) : <p className="muted">No arrivals waiting today.</p>}</div><div className="panel"><div className="panel-head"><h2>Departures</h2><span>{data.departures.length}</span></div>{data.departures.length ? data.departures.map(r => card(r, 'departure')) : <p className="muted">No departures due today.</p>}</div><div className="panel"><div className="panel-head"><h2>In house</h2><span>{data.in_house.length}</span></div>{data.in_house.length ? data.in_house.map(r => card(r, 'in-house')) : <p className="muted">No checked-in guests.</p>}</div></div></section>;
}

function RoomsView({ user, rooms, setRooms, roomTypes, onRefresh }: { user: User; rooms: Room[]; setRooms: React.Dispatch<React.SetStateAction<Room[]>>; roomTypes: RoomType[]; onRefresh: () => Promise<void> }) {
  const [filter, setFilter] = useState('all'); const [message, setMessage] = useState(''); const [typeName, setTypeName] = useState(''); const [rate, setRate] = useState(''); const [typeDescription, setTypeDescription] = useState(''); const [roomNumber, setRoomNumber] = useState(''); const [roomTypeId, setRoomTypeId] = useState('');
  const typeById = useMemo(() => new Map(roomTypes.map(t => [t.id, t])), [roomTypes]); const visibleRooms = filter === 'all' ? rooms : rooms.filter(r => r.status === filter); const isAdmin = user.role === 'admin';
  async function createType(e: React.FormEvent) { e.preventDefault(); try { await api('/api/room-types', { method: 'POST', body: JSON.stringify({ name: typeName, base_rate: Number(rate || 0), description: typeDescription || null }) }); setTypeName(''); setRate(''); setTypeDescription(''); setMessage('Room type created.'); await onRefresh(); } catch (err) { setMessage(err instanceof Error ? err.message : 'Unable to create room type'); } }
  async function createRoom(e: React.FormEvent) { e.preventDefault(); try { await api('/api/rooms', { method: 'POST', body: JSON.stringify({ number: roomNumber, room_type_id: Number(roomTypeId) }) }); setRoomNumber(''); setRoomTypeId(''); setMessage('Room added.'); await onRefresh(); } catch (err) { setMessage(err instanceof Error ? err.message : 'Unable to create room'); } }
  async function changeStatus(room: Room, nextStatus: string) { try { const updated = await api<Room>(`/api/rooms/${room.id}/status`, { method: 'PATCH', body: JSON.stringify({ status: nextStatus }) }); setRooms(current => current.map(r => r.id === updated.id ? updated : r)); setMessage(`Room ${updated.number} is now ${nextStatus.replace(/_/g, ' ')}.`); } catch (err) { setMessage(err instanceof Error ? err.message : 'Unable to change room status'); } }
  return <section className="page"><div className="page-heading"><div><p className="muted">Inventory & housekeeping</p><h2>Rooms</h2></div><span className="room-count">{rooms.length} rooms</span></div>{message && <p className="notice">{message}</p>}<div className="room-layout"><div className="panel room-map-panel"><div className="panel-head"><h2>Room map</h2><select value={filter} onChange={e => setFilter(e.target.value)}><option value="all">All statuses</option>{statuses.map(status => <option key={status} value={status}>{status.replace(/_/g, ' ')}</option>)}</select></div><div className="room-map">{visibleRooms.length ? visibleRooms.map(room => <article className={`room-card room-${room.status}`} key={room.id}><div className="room-card-top"><strong>{room.number}</strong><span>{typeById.get(room.room_type_id)?.name ?? 'Unknown type'}</span></div><small>{typeById.get(room.room_type_id) ? `Rate ${Number(typeById.get(room.room_type_id)!.base_rate).toFixed(2)}` : 'No rate'}</small><select value={room.status} onChange={e => changeStatus(room, e.target.value)} disabled={user.role !== 'admin' && user.role !== 'reception' && user.role !== 'housekeeping'}>{statuses.map(status => <option key={status} value={status}>{status.replace(/_/g, ' ')}</option>)}</select></article>) : <p className="muted">No rooms match this filter.</p>}</div></div><div className="side-stack"><div className="panel"><div className="panel-head"><h2>Room types</h2><span>{roomTypes.length}</span></div>{roomTypes.length ? <div className="type-list">{roomTypes.map(type => <div key={type.id}><div><strong>{type.name}</strong><span>{type.description || 'No description'}</span></div><b>{Number(type.base_rate).toFixed(2)}</b></div>)}</div> : <p className="muted">Create your first room type.</p>}</div>{isAdmin && <><form className="panel form-panel" onSubmit={createType}><div className="panel-head"><h2>Add room type</h2></div><label>Name<input value={typeName} onChange={e => setTypeName(e.target.value)} required /></label><label>Base rate<input type="number" min="0" step="0.01" value={rate} onChange={e => setRate(e.target.value)} required /></label><label>Description<textarea value={typeDescription} onChange={e => setTypeDescription(e.target.value)} rows={2} /></label><button className="primary-button">Create room type</button></form><form className="panel form-panel" onSubmit={createRoom}><div className="panel-head"><h2>Add room</h2></div><label>Room number<input value={roomNumber} onChange={e => setRoomNumber(e.target.value)} placeholder="101" required /></label><label>Room type<select value={roomTypeId} onChange={e => setRoomTypeId(e.target.value)} required><option value="">Select type</option>{roomTypes.map(type => <option key={type.id} value={type.id}>{type.name}</option>)}</select></label><button className="primary-button" disabled={!roomTypes.length}>Add room</button></form></>}</div></div></section>;
}

function App() {
  const [user, setUser] = useState<User | null>(null); const [authMode, setAuthMode] = useState<AuthMode>('login'); const [checkingAuth, setCheckingAuth] = useState(true); const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [rooms, setRooms] = useState<Room[]>([]); const [roomTypes, setRoomTypes] = useState<RoomType[]>([]); const [guests, setGuests] = useState<Guest[]>([]); const [reservations, setReservations] = useState<Reservation[]>([]); const [frontDesk, setFrontDesk] = useState<FrontDeskData>({ arrivals: [], departures: [], in_house: [] }); const [view, setView] = useState<View>('Dashboard'); const [error, setError] = useState('');
  async function loadHotelData() { const [d, r, rt, g, rs, fd] = await Promise.all([api<Dashboard>('/api/dashboard'), api<Room[]>('/api/rooms'), api<RoomType[]>('/api/room-types'), api<Guest[]>('/api/guests'), api<Reservation[]>('/api/reservations'), api<FrontDeskData>('/api/front-desk')]); setDashboard(d); setRooms(r); setRoomTypes(rt); setGuests(g); setReservations(rs); setFrontDesk(fd); }
  useEffect(() => { const token = localStorage.getItem(TOKEN_KEY); if (!token) { api<{ initialized: boolean }>('/api/auth/setup-status').then(s => setAuthMode(s.initialized ? 'login' : 'bootstrap')).catch(() => setError('Backend is not running.')).finally(() => setCheckingAuth(false)); return; } api<User>('/api/auth/me').then(setUser).catch(() => localStorage.removeItem(TOKEN_KEY)).finally(() => setCheckingAuth(false)); }, []);
  useEffect(() => { if (!user) return; setError(''); loadHotelData().catch(err => { if ((err as Error & { status?: number }).status === 401) handleLogout(); else setError(err instanceof Error ? err.message : 'Unable to load hotel data'); }); }, [user]);
  function handleAuthenticated(nextUser: User, token: string) { localStorage.setItem(TOKEN_KEY, token); setUser(nextUser); setView('Dashboard'); }
  function handleLogout() { localStorage.removeItem(TOKEN_KEY); setUser(null); setDashboard(null); setRooms([]); setRoomTypes([]); setGuests([]); setReservations([]); setFrontDesk({ arrivals: [], departures: [], in_house: [] }); setAuthMode('login'); }
  if (checkingAuth) return <main className="auth-shell"><p className="muted">Checking local session…</p></main>;
  if (!user) return <AuthScreen mode={authMode} setMode={setAuthMode} onAuthenticated={handleAuthenticated} />;
  return <main className="shell"><header className="topbar"><div><p className="eyebrow">LA SERENE HOTEL</p><h1>Hotel Management System</h1></div><div className="user-actions"><div className="user-chip"><strong>{user.username}</strong><span>{user.role}</span></div><button className="logout-button" onClick={handleLogout}>Log out</button></div></header><nav className="module-nav">{modules.map(item => <button key={item} className={view === item ? 'active' : ''} onClick={() => setView(item)}>{item}</button>)}</nav><section className="welcome"><div><p className="muted">{view === 'Rooms' ? 'Room inventory, rates and housekeeping' : view === 'Front Desk' ? 'Guest movement and desk operations' : view === 'Guests' ? 'Guest records and profiles' : view === 'Reservations' ? 'Bookings and availability' : 'Operations dashboard'}</p><h2>{dashboard ? `Business date · ${dashboard.business_date}` : 'Loading hotel data…'}</h2></div>{error && <p className="error">{error}</p>}</section>{view === 'Dashboard' && <DashboardView dashboard={dashboard} rooms={rooms} roomTypes={roomTypes} />}{view === 'Rooms' && <RoomsView user={user} rooms={rooms} setRooms={setRooms} roomTypes={roomTypes} onRefresh={loadHotelData} />}{view === 'Guests' && <GuestsView user={user} guests={guests} setGuests={setGuests} onRefresh={loadHotelData} />}{view === 'Reservations' && <ReservationsView user={user} guests={guests} rooms={rooms} roomTypes={roomTypes} reservations={reservations} onRefresh={loadHotelData} />}{view === 'Front Desk' && <FrontDeskView user={user} data={frontDesk} rooms={rooms} onRefresh={loadHotelData} />}</main>;
}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
